version: '3.7'
services:
    mysql:
        image: mysql:latest
        ports:
            - '3306:3306'

        volumes:
            - ./schema:/docker-entrypoint-initdb.d

        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=pass

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"

        volumes:
            - ./schema:/docker-entrypoint-initdb.d

        environment:
            - POSTGRES_RANDOM_ROOT_PASSWORD=yes
            - POSTGRES_DB=app
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=pass

    nodejs:
        build: ./gate-simulator
        ports:
            - '9999:9999'